language: go

go:
  - 1.6
  - 1.7
  - 1.8

before_install:
  - go get -t ./...

script:
  - export LAMP_CONFIG_PATH=$PWD/contrib
  - go test -race -coverprofile=coverage.txt -covermode=atomic -timeout 30s

after_success:
  - bash <(curl -s https://codecov.io/bash)
